In [4]:
import pandas as pd

In [10]:
fil_nm = "../../MSDS_453_Public/MSDS453_ClassCorpus/ClassCorpus_Final_v2_20220629.csv"

In [11]:
df = pd.read_csv(fil_nm)

In [12]:
df

,Doc_ID,DSI_Title,Text,Submission File Name,Student Name,Genre of Movie,Review Type (pos or neg),Movie Title
0,160,ARE_Doc1_Taxi,Jimmy Fallon's big screen career may be over b...,ARE_Doc1_Taxi,ARE,Action,Negative,Taxi
1,161,ARE_Doc2_Taxi,"After getting nominated for ""Chicago"" and maki...",ARE_Doc2_Taxi,ARE,Action,Positive,Taxi
2,162,ARE_Doc3_Taxi,Queen Latifah handily walked away with the sho...,ARE_Doc3_Taxi,ARE,Action,Negative,Taxi
3,163,ARE_Doc4_Taxi,So Jimmy Fallon leaves ÒSaturday Night LiveÓ a...,ARE_Doc4_Taxi,ARE,Action,Negative,Taxi
4,164,ARE_Doc5_Taxi,TaxiÊcasts JimmyÊFallon as Officer Andy Washbu...,ARE_Doc5_Taxi,ARE,Action,Negative,Taxi
...,...,...,...,...,...,...,...,...
195,85,MGB_Doc6_Inception,Inception makes the average moviegoer feel sma...,MGB_Doc6_Inception,MGB,Action,Negative,Inception
196,86,MGB_Doc7_Inception,"You have this basic idea and the story, they a...",MGB_Doc7_Inception,MGB,Action,Negative,Inception
197,87,MGB_Doc8_Inception,Unless you call this movie a masterpiece. Then...,MGB_Doc8_Inception,MGB,Action,Negative,Inception
198,88,MGB_Doc9_Inception,After reading all the amazing reviews and seei...,MGB_Doc9_Inception,MGB,Action,Negative,Inception
199,89,MGB_Doc10_Inception,A shame that this movie is rated so highly on ...,MGB_Doc10_Inception,MGB,Action,Negative,Inception

In [13]:
len(df['Student Name'].unique())

20